// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TabelaTPL.Context;

#nullable disable

namespace TabelaTPL.Migrations
{
    [DbContext(typeof(TabelaContext))]
    partial class TabelaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TabelaTPL.Models.Disponibilidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Disponibilidades")
                        .HasColumnType("int");

                    b.Property<int>("VoluntariosId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoluntariosId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("TabelaTPL.Models.Voluntarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Informacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Voluntarios");
                });

            modelBuilder.Entity("TabelaTPL.Models.Disponibilidade", b =>
                {
                    b.HasOne("TabelaTPL.Models.Voluntarios", "Voluntarios")
                        .WithMany("Disponibilidade")
                        .HasForeignKey("VoluntariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voluntarios");
                });

            modelBuilder.Entity("TabelaTPL.Models.Voluntarios", b =>
                {
                    b.Navigation("Disponibilidade");
                });
#pragma warning restore 612, 618
        }
    }
}
